package com.ab.tasktracker.exception;

public enum ErrorCode {
    INTERNAL_ERROR,
    TASK_NOT_FOUND,
    TASK_FETCH_ERROR,
    SAVE_DATA_IN_DB_ERROR,
    METHOD_ARGUMENT_NOT_VALID,
    TYPE_SENSE_CONNECTION_ERROR,
    AUTHENTICATION_REQUIRED,
    SECURITY_EXCEPTION,
    XSS_EXCEPTION,
    DATE_EXCEPTION,
    USER_NOT_FOUND,
    USER_ID_REQUIRED

}
